database:
  driverName: org.h2.Driver
  url: jdbc:h2:mem:storage;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:
  hibernateDialect: org.hibernate.dialect.H2Dialect
  hibernateShowSql: true
  hibernateHbm2ddl: create